export const communities = [
  {
    icon: "🧑‍💻",
    title: "recommended.frontend.title",
    desc: "recommended.frontend.desc",
    members: 1342,
  },
  {
    icon: "📚",
    title: "recommended.readers.title",
    desc: "recommended.readers.desc",
    members: 847,
  },
  {
    icon: "💬",
    title: "recommended.chat.title",
    desc: "recommended.chat.desc",
    members: 560,
  },
  {
    icon: "📸",
    title: "recommended.photographers.title",
    desc: "recommended.photographers.desc",
    members: 234,
  },
  {
    icon: "🎨",
    title: "recommended.designers.title",
    desc: "recommended.designers.desc",
    members: 786,
  },
  {
    icon: "💼",
    title: "recommended.startup.title",
    desc: "recommended.startup.desc",
    members: 491,
  },
  {
    icon: "🧠",
    title: "recommended.selfdev.title",
    desc: "recommended.selfdev.desc",
    members: 1392,
  },
  {
    icon: "🎵",
    title: "recommended.music.title",
    desc: "recommended.music.desc",
    members: 314,
  },
  {
    icon: "🎮",
    title: "recommended.gamers.title",
    desc: "recommended.gamers.desc",
    members: 728,
  },
  {
    icon: "🌐",
    title: "recommended.english.title",
    desc: "recommended.english.desc",
    members: 1503,
  },
  {
    icon: "🧘",
    title: "recommended.mental.title",
    desc: "recommended.mental.desc",
    members: 376,
  },
  {
    icon: "📈",
    title: "recommended.finance.title",
    desc: "recommended.finance.desc",
    members: 598,
  },
  {
    icon: "⚙️",
    title: "recommended.tech.title",
    desc: "recommended.tech.desc",
    members: 1049,
  },
  {
    icon: "✍️",
    title: "recommended.writers.title",
    desc: "recommended.writers.desc",
    members: 218,
  },
  {
    icon: "🏃",
    title: "recommended.sport.title",
    desc: "recommended.sport.desc",
    members: 467,
  },
]