export const communities = [
  {
    icon: "🧑‍💻",
    title: "frontend.title",
    desc: "frontend.desc",
    members: 1342,
  },
  {
    icon: "📚",
    title: "readers.title",
    desc: "readers.desc",
    members: 847,
  },
  {
    icon: "💬",
    title: "chat.title",
    desc: "chat.desc",
    members: 560,
  },
  {
    icon: "📸",
    title: "photographers.title",
    desc: "photographers.desc",
    members: 234,
  },
  {
    icon: "🎨",
    title: "designers.title",
    desc: "designers.desc",
    members: 786,
  },
  {
    icon: "💼",
    title: "startup.title",
    desc: "startup.desc",
    members: 491,
  },
  {
    icon: "🧠",
    title: "selfdev.title",
    desc: "selfdev.desc",
    members: 1392,
  },
  {
    icon: "🎵",
    title: "music.title",
    desc: "music.desc",
    members: 314,
  },
  {
    icon: "🎮",
    title: "gamers.title",
    desc: "gamers.desc",
    members: 728,
  },
  {
    icon: "🌐",
    title: "english.title",
    desc: "english.desc",
    members: 1503,
  },
  {
    icon: "🧘",
    title: "mental.title",
    desc: "mental.desc",
    members: 376,
  },
  {
    icon: "📈",
    title: "finance.title",
    desc: "finance.desc",
    members: 598,
  },
  {
    icon: "⚙️",
    title: "tech.title",
    desc: "tech.desc",
    members: 1049,
  },
  {
    icon: "✍️",
    title: "writers.title",
    desc: "writers.desc",
    members: 218,
  },
  {
    icon: "🏃",
    title: "sport.title",
    desc: "sport.desc",
    members: 467,
  },
]